clouds = off
dynamicHandLight = false
oldHandLight = false
oldLighting = false
separateAo = true
underwaterOverlay = false
shadowTranslucent = true
sun = false
moon = true
stars = false
vignette = false
frustum.culling = true
shadow.culling = false

iris.features.optional = SSBO

blend.gbuffers_basic = ONE ZERO ONE ZERO
blend.gbuffers_textured = ONE ZERO ONE ZERO
blend.gbuffers_textured_lit = ONE ZERO ONE ZERO
blend.gbuffers_skybasic = ONE ZERO ONE ZERO
blend.gbuffers_skytextured = ONE ZERO ONE ZERO
blend.gbuffers_terrain = ONE ZERO ONE ZERO
blend.gbuffers_damagedblock = ONE ZERO ONE ZERO
blend.gbuffers_entities = ONE ZERO ONE ZERO
blend.gbuffers_armor_glint = ONE ZERO ONE ZERO
blend.gbuffers_spidereyes = ONE ZERO ONE ZERO
blend.gbuffers_hand = ONE ZERO ONE ZERO
blend.shadow = ONE ZERO ONE ZERO

alphaTest.gbuffers_water = off

blend.gbuffers_weather = ONE ONE ONE ZERO
blend.gbuffers_water = ONE ZERO ONE ZERO
blend.gbuffers_hand_water = ONE ZERO ONE ZERO

texture.noise = texture/stbn.png

#ifdef SSPT
bufferObject.0 = 16 true 1.0 1.0
#endif

uniform.float.isRain = smooth(102, if(in(biome_precipitation, 1), 1, 0), 20, 10)

uniform.vec2.viewSize = vec2(viewWidth, viewHeight)
uniform.vec2.invViewSize = vec2(1.0 / viewWidth, 1.0 / viewHeight)

variable.int.taaJitterIndex = frameCounter % 16
uniform.vec2.taaJitter = vec2((if( \
	taaJitterIndex ==  0,   0.0  / 16.0,  taaJitterIndex ==  1,  -8.0  / 16.0, \
	taaJitterIndex ==  2,   2.0  / 16.0,  taaJitterIndex ==  3,  -10.0 / 16.0, \
	taaJitterIndex ==  4,   12.0 / 16.0,  taaJitterIndex ==  5,  -4.0  / 16.0, \
	taaJitterIndex ==  6,   14.0 / 16.0,  taaJitterIndex ==  7,  -6.0  / 16.0, \
	taaJitterIndex ==  8,  -3.0  / 16.0,  taaJitterIndex ==  9,   11.0 / 16.0, \
	taaJitterIndex == 10,  -1.0  / 16.0,  taaJitterIndex == 11,   9.0  / 16.0, \
	taaJitterIndex == 12,  -15.0 / 16.0,  taaJitterIndex == 13,   7.0  / 16.0, \
	taaJitterIndex == 14,  -13.0 / 16.0,  taaJitterIndex == 15,   5.0  / 16.0, \
	0.0) \
) / viewWidth, \
(if( \
	taaJitterIndex ==  0,  -3.0  / 16.0,  taaJitterIndex ==  1,   11.0 / 16.0, \
	taaJitterIndex ==  2,   1.0  / 16.0,  taaJitterIndex ==  3,  -9.0  / 16.0, \
	taaJitterIndex ==  4,  -15.0 / 16.0,  taaJitterIndex ==  5,   7.0  / 16.0, \
	taaJitterIndex ==  6,   13.0 / 16.0,  taaJitterIndex ==  7,  -5.0  / 16.0, \
	taaJitterIndex ==  8,   0.0  / 16.0,  taaJitterIndex ==  9,  -8.0  / 16.0, \
	taaJitterIndex == 10,  -2.0  / 16.0,  taaJitterIndex == 11,   10.0 / 16.0, \
	taaJitterIndex == 12,   12.0 / 16.0,  taaJitterIndex == 13,  -4.0  / 16.0, \
	taaJitterIndex == 14,  -14.0 / 16.0,  taaJitterIndex == 15,   6.0  / 16.0, \
	0.0) \
) / viewHeight)

screen = INFOMATION <empty> [LIGHTING] [SURFACE]
screen.columns = 1

screen.LIGHTING = [SSPT]
screen.LIGHTING.columns = 1

screen.SSPT = SSPT SSPT_INTENSITY SSPT_MAX_FRAMES
screen.SSPT.columns = 1

screen.SURFACE = RAIN_PUDDLES [POM]
screen.SURFACE.columns = 1

screen.POM = PARALLAX POM_STEPS POM_REFINEMENT_STEPS POM_DEPTH_SCALE <empty> PARALLAX_SHADOW POM_SHADOW_STEPS POM_SHADOW_SOFTNESS
screen.POM.columns = 1

sliders = POM_STEPS POM_REFINEMENT_STEPS POM_DEPTH_SCALE POM_SHADOW_STEPS POM_SHADOW_SOFTNESS SSPT_INTENSITY SSPT_MAX_FRAMES